Added directory check function

diff --git a/.local/bin/game b/.local/bin/game
--- a/.local/bin/game
+++ b/.local/bin/game
@@ -64,6 +64,14 @@ read_file() {
 	#remove_temp_file
 }
 
+check_dir() {
+	if [ -d "$1" ]; then
+		return 0
+	else
+		return 1
+	fi
+}
+
 backup_saves() {
 	create_temp_file "$save_locations"
 	while read line; do
@@ -71,7 +79,11 @@ backup_saves() {
 		game_save=$(echo $line | awk -F',' '{print $2}')
 		game_backup=$(echo $line | awk -F',' '{print $3}')
 		echo "Backing up $game_title..."
-		cp -r -p -v --update "$game_save/." "$game_backup" || echo "Nothing to do"
+		if ! check_dir "$game_save"; then
+			echo "'$game_save' not found.  Try restoring."
+			exit 1
+		fi
+		cp -r -p -v --update "$game_save/." "$game_backup"
 		#rsync -r -n --progress -t --delete --modify-window=1 "$game_save/" "$game_backup"
 		echo
 	done < $temp_file
@@ -91,6 +103,13 @@ archive_saves() {
 		echo
 	done < $temp_file
 	remove_temp_file
+}
+
+# Restore a save game
+restore_save() {
+	# Remove last argument
+	unset 'argv[-1]'
+	grep -i "$@" "$save_locations" 
 }
 
 get_args() {
