Update decksync Experimenting with directory checking. Still a work in progress. Added dry-run mode.

diff --git a/.local/bin/steamdeck/decksync b/.local/bin/steamdeck/decksync
--- a/.local/bin/steamdeck/decksync
+++ b/.local/bin/steamdeck/decksync
@@ -20,6 +20,7 @@ set -euo pipefail
 #     directory does not exist.  Chaning the cfg file to "/home/whatever/" fixes this problem, but I want
 #     to find how to fix it here.
 # - Add some more comments.
+# - Fix bug where if a directory is not found, the script will exit.
 
 
 
@@ -61,6 +62,7 @@ mirror_args=(
 	--verbose
 	--exclude-glob *.cfg
 	--dereference
+	--allow-suid
 )
 
 
@@ -155,6 +157,13 @@ pc_to_deck() {
 		mirror_command="mirror ${mirror_args[@]} --reverse \"$pc_directory\" \"$deck_directory\""
 	fi
 
+	# Check if remote directory exists
+	#local does_dir_exist=$(check_directories "$pc_directory")
+	#if [ "$does_dir_exist" -eq 0 ]; then
+	#	echo "PC directory not found.  Skipping."
+	#	return
+	#fi
+
 	# Call to lftp
 	lftp -c "
 	open $HOST
@@ -198,6 +207,13 @@ deck_to_pc() {
 		mirror_command="mirror ${mirror_args[@]} \"$deck_directory\" \"$pc_directory\""
 	fi
 
+	# Check if remote directory exists
+	#local does_dir_exist=$(check_directories "$deck_directory")
+	#if [ "$does_dir_exist" -eq 0 ]; then
+	#	echo "Deck directory not found.  Skipping."
+	#	return
+	#fi
+
 	# Call to lftp
 	lftp -c "
 	open $HOST
@@ -237,6 +253,22 @@ check_pc_saves() {
 
 	echo "$number_of_files"
 
+}
+
+function check_directories() {
+	local dir_to_check="$1"
+	local exists=0
+	lftp -c "
+	open $HOST
+	user $USER $PASS
+	glob -d --exist \"$dir_to_check\" && echo 1 || echo 0
+	"
+
+	#if [ -d "$dir_to_check" ]; then
+	#	exists=1
+	#fi
+
+	#echo "$exists"
 }
 
 # Sync saves
@@ -293,7 +325,7 @@ sync_saves() {
 			pc_to_deck "$pc_save" "$deck_save"
 			echo
 			deck_to_pc "$pc_save" "$deck_save"
-			
+
 		fi
 
 		# Add a footer.
@@ -305,6 +337,17 @@ sync_saves() {
 
 	done
 
+}
+
+
+# Once a dry-run is complete, prompt the user if they wish to run the script again, but for real.
+function run_after_dry_run() {
+	# If delete mode was used during the dry-run, preserve the setting.
+	if [ $delete_mode -eq 1 ]; then
+		decksync -d
+	else
+		decksync
+	fi
 }
 
 
@@ -405,14 +448,14 @@ main() {
 	parse_conf
 	sync_saves
 
-	# Once a dry-run is complete, prompt the user if they wish to run the script again, but for real.
+	# If dry-run mode was used, ask the user if they would like to run the script again for real.
 	if [ $dry_run_mode -eq 1 ]; then
 		echo "Dry-Run complete."
 		yes_or_no "Would you like to run the script for real?" || exit
 		echo
-		decksync
+		run_after_dry_run
 	fi
-		
+
 }
 
 ####################
